### Get all categories
GET https://category.iamrisk.my.id/api/categories
Accept: application/json
X-API-Key: RAHASIA

### Create New Category
POST https://category.iamrisk.my.id/api/categories
Accept: application/json
Content-Type: application/json
X-API-Key: RAHASIA

{
    "name": "Electronic"
}

### Get Category by Id
GET https://category.iamrisk.my.id/api/categories/2
Accept: application/json
X-API-Key: RAHASIA

### Update Category
PUT https://category.iamrisk.my.id/api/categories/2
Accept: application/json
Content-Type: application/json
X-API-Key: RAHASIA

{
    "name": "Laptop"
}

### Delete Category
DELETE https://category.iamrisk.my.id/api/categories/5
Accept: application/json
X-API-Key: RAHASIA